name: Full Stack Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v4
        with:
          repository: CloudTechDevOps/Java-springboot-project
          ref: main

      ################################################
      # FRONTEND (STREAMLIT)
      ################################################
      - name: Verify Python
        run: |
            which python3
            python3 --version
            pip3 --version
      

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Stop Existing Frontend
        run: |
          pkill -f "streamlit run" || true

      - name: Start Frontend
        run: |
          cd frontend
          nohup streamlit run app.py \
            --server.address=0.0.0.0 \
            --server.port=8501 \
            > streamlit.log 2>&1 &

      ################################################
      # BACKEND (SPRING BOOT)
      ################################################

      - name: Build Backend
        run: |
          cd backend
          mvn clean package -DskipTests

      - name: Stop Existing Backend
        run: |
          pkill -f "java -jar" || true

      - name: Start Backend
        run: |
          cd backend/target
          nohup java -jar *.jar > backend.log 2>&1 &
